### ISSUE TITLE
I really like your project and wanted to ask you.,

### ISSUE THREAD

**Issue by Toni-d-e-v** [ljedrz/pea2pea#14]
I don't  want to bother you sir but can you please just show me how to code a p2pnode that just connects and gets peers then have functions like broadcast_message and direct message I cant find that example thanks.

**Comment by Toni-d-e-v** [comment]
Also if you help I may donate some crypto to your project

**Comment by ljedrz** [comment]
Happy to provide some guidance.
The existing examples can probably be "squeezed" a little bit, but in order to achieve meaningful communication, you'll still need to implement the `Reading` and `Writing` protocols; getting peers also depends on the network (some use DHTs, some have messages with lists of peers). My point is that what you're describing already requires a bit of a specific setup, which might not be the one you're after. Have you looked at the tests? There are some examples of basic functionalities there, you might be able to build something based on them.

**Comment by Toni-d-e-v** [comment]
Hi, how hard would it be implementing send_direct_message and broadcast message, and add message handler in the secure node? https://github.com/ljedrz/pea2pea/blob/master/examples/noise_handshake.rs

**Comment by ljedrz** [comment]
Those methods are already available thanks to `Writing` being implemented; note that `send_direct_message` is being used.
